"""generate_simple_docs.py – creates a child‑friendly PDF.
It reads the two simplified markdown files (SIMPLE_DOCUMENTATION.md and
SIMPLE_RUNNING.md) and renders them with reportlab.
"""
from pathlib import Path
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.platypus import SimpleDocTemplate, Paragraph, Preformatted, Spacer

# Source markdown files (simple language)
DOC_MD = Path(__file__).parent / "SIMPLE_DOCUMENTATION.md"
RUN_MD = Path(__file__).parent / "SIMPLE_RUNNING.md"
OUTPUT_PDF = Path(__file__).parent / "Capital_Trader_Simple_Documentation.pdf"

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name="TitleLarge", parent=styles["Title"], fontSize=24, leading=28, alignment=TA_LEFT))
styles.add(ParagraphStyle(name="CodeBlock", parent=styles["Normal"], fontName="Courier", fontSize=9, leading=12))


def markdown_to_flowables(md_path: Path):
    """Very light markdown → reportlab flowables.
    Splits on triple backticks for code blocks.
    """
    text = md_path.read_text(encoding="utf-8")
    parts = text.split("```")
    flow = []
    for i, part in enumerate(parts):
        if i % 2 == 0:
            for para in part.strip().split("\n\n"):
                if para.strip():
                    flow.append(Paragraph(para.replace("\n", " "), styles["Normal"]))
                    flow.append(Spacer(1, 6))
        else:
            flow.append(Preformatted(part.strip('\n'), styles["CodeBlock"]))
            flow.append(Spacer(1, 6))
    return flow


def build_pdf():
    doc = SimpleDocTemplate(str(OUTPUT_PDF), pagesize=LETTER, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    flowables = []
    flowables.append(Paragraph("Capital.com Async Trading Platform – Simple Guide", styles["TitleLarge"]))
    flowables.append(Spacer(1, 24))
    flowables.append(Paragraph("Generated by Claude Code on 2026‑05‑09", styles["Normal"]))
    flowables.append(Spacer(1, 48))
    flowables.extend(markdown_to_flowables(DOC_MD))
    flowables.append(Spacer(1, 24))
    flowables.append(Paragraph("---", styles["Normal"]))
    flowables.append(Spacer(1, 24))
    flowables.extend(markdown_to_flowables(RUN_MD))
    doc.build(flowables)
    print(f"Simple PDF generated at {OUTPUT_PDF}")

if __name__ == "__main__":
    build_pdf()
