"""generate_docs.py – creates a PDF with the two markdown files.
It uses reportlab to render normal paragraphs and pre‑formatted code blocks.
"""
from pathlib import Path
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.platypus import SimpleDocTemplate, Paragraph, Preformatted, Spacer

# Paths to the source markdown files (relative to this script)
DOC_MD = Path(__file__).parent / "DOCUMENTATION.md"
RUN_MD = Path(__file__).parent / "RUNNING.md"
OUTPUT_PDF = Path(__file__).parent / "Capital_Trader_Documentation.pdf"

styles = getSampleStyleSheet()
# Slightly larger for titles
styles.add(ParagraphStyle(name="TitleLarge", parent=styles["Title"], fontSize=24, leading=28, alignment=TA_LEFT))
styles.add(ParagraphStyle(name="CodeBlock", parent=styles["Normal"], fontName="Courier", fontSize=9, leading=12))


def markdown_to_flowables(md_path: Path):
    """Very light Markdown → reportlab flowables.
    Splits on triple backticks to separate code blocks.
    """
    text = md_path.read_text(encoding="utf-8")
    parts = text.split("```")
    flow = []
    for i, part in enumerate(parts):
        if i % 2 == 0:
            # normal markdown – we ignore headings markup and just treat as plain text
            # split into paragraphs on double newlines
            for para in part.strip().split("\n\n"):
                if para.strip():
                    flow.append(Paragraph(para.replace("\n", " "), styles["Normal"]))
                    flow.append(Spacer(1, 6))
        else:
            # code block – keep indentation and line breaks
            flow.append(Preformatted(part.strip('\n'), styles["CodeBlock"]))
            flow.append(Spacer(1, 6))
    return flow


def build_pdf():
    doc = SimpleDocTemplate(str(OUTPUT_PDF), pagesize=LETTER, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    flowables = []
    # Title page
    flowables.append(Paragraph("Capital.com Async Trading Platform – Documentation", styles["TitleLarge"]))
    flowables.append(Spacer(1, 24))
    flowables.append(Paragraph("Generated by Claude Code on 2026‑05‑09", styles["Normal"]))
    flowables.append(Spacer(1, 48))
    # Add the two markdown documents
    flowables.extend(markdown_to_flowables(DOC_MD))
    flowables.append(Spacer(1, 24))
    flowables.append(Paragraph("---", styles["Normal"]))
    flowables.append(Spacer(1, 24))
    flowables.extend(markdown_to_flowables(RUN_MD))
    doc.build(flowables)

if __name__ == "__main__":
    build_pdf()
    print(f"PDF generated at {OUTPUT_PDF}")
