"""initial

Revision ID: 2511bca9ec79
Revises: 
Create Date: 2026-05-09 12:09:55.005338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2511bca9ec79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('epic', sa.String(), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('notification_channel', sa.String(), nullable=True),
    sa.Column('active', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_epic'), 'alerts', ['epic'], unique=False)
    op.create_table('candles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('epic', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bid_close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ask_close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candles_candle_time'), 'candles', ['candle_time'], unique=False)
    op.create_index(op.f('ix_candles_epic'), 'candles', ['epic'], unique=False)
    op.create_table('dead_letter_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('retry_count', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_events_event_type'), 'dead_letter_events', ['event_type'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('epic', sa.String(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('limit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('broker_order_id', sa.String(), nullable=True),
    sa.Column('client_order_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_index(op.f('ix_orders_epic'), 'orders', ['epic'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('epic', sa.String(), nullable=True),
    sa.Column('size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deal_reference', sa.String(), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_epic'), 'positions', ['epic'], unique=False)
    op.create_table('trade_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_logs_correlation_id'), 'trade_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_trade_logs_event_type'), 'trade_logs', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_logs_event_type'), table_name='trade_logs')
    op.drop_index(op.f('ix_trade_logs_correlation_id'), table_name='trade_logs')
    op.drop_table('trade_logs')
    op.drop_index(op.f('ix_positions_epic'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_epic'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_dead_letter_events_event_type'), table_name='dead_letter_events')
    op.drop_table('dead_letter_events')
    op.drop_index(op.f('ix_candles_epic'), table_name='candles')
    op.drop_index(op.f('ix_candles_candle_time'), table_name='candles')
    op.drop_table('candles')
    op.drop_index(op.f('ix_alerts_epic'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
